#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 SQLite Cloud, Inc.
"""
gen_xtml_goldens.py — freeze the K3 prompt corpus.

The differential check in tests/serve/test_xtml.py needs the release's
encoding_k3.py on disk. Most machines do not have 983 GB of Kimi K3 lying
around, so this renders the corpus once, on a machine that does, and writes
the result where the test can find it without the disk.

Goldens come from **upstream's encoder** when it is available, and the file
records which it was. A golden generated by our own renderer would lock in
whatever it currently does, including its bugs, so the test refuses to
treat that as evidence.

  K3_DIR=/Volumes/WasteDisk/k3 python3 tools/gen_xtml_goldens.py
"""

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tests.serve.corpus import CASES                       # noqa: E402

DEFAULT_OUT = ROOT / "tests" / "serve" / "fixtures" / "xtml_golden.json"


def load_upstream(k3_dir: str):
    """Import the release's encoding_k3.py from an arbitrary path.

    Registered in sys.modules before exec: @dataclass resolves its own
    module through sys.modules while the class body runs, and a module
    that is not there yet makes it fail with a bare AttributeError.
    """
    path = Path(k3_dir) / "encoding_k3.py"
    if not path.exists():
        return None
    import importlib.util
    name = "_upstream_encoding_k3"
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--k3-dir", default=os.environ.get("K3_DIR",
                                                       "/Volumes/WasteDisk/k3"),
                    help="release directory holding encoding_k3.py")
    ap.add_argument("-o", "--out", default=str(DEFAULT_OUT))
    ap.add_argument("--allow-ours", action="store_true",
                    help="write goldens from our own renderer when the "
                         "release is absent (they then prove nothing about "
                         "matching K3 — the test says so)")
    args = ap.parse_args()

    upstream = load_upstream(args.k3_dir)
    if upstream is not None:
        render = lambda case: [[s.text, s.allow_special]                # noqa: E731
                               for s in upstream.build_chat_segments(**case)]
        source = f"{args.k3_dir}/encoding_k3.py"
        print(f"rendering {len(CASES)} cases with the release's encoder")
    else:
        if not args.allow_ours:
            print(f"no encoding_k3.py under {args.k3_dir}.\n"
                  f"Point --k3-dir at the release, or pass --allow-ours to "
                  f"write goldens from serve/xtml.py itself (which then only "
                  f"catches regressions, not divergence from K3).",
                  file=sys.stderr)
            return 1
        from serve import xtml
        render = lambda case: [[s.text, s.markup]                       # noqa: E731
                               for s in xtml.build_chat_segments(**case)]
        source = "serve/xtml.py"
        print("WARNING: the release is not on disk; goldens come from our "
              "own renderer", file=sys.stderr)

    cases = {}
    for name, case in CASES:
        cases[name] = render(case)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "comment": "Generated by tools/gen_xtml_goldens.py — do not edit. "
                   "Segments are [text, is_markup] pairs.",
        "from_upstream": upstream is not None,
        "source": source,
        "cases": cases,
    }, ensure_ascii=False, indent=1) + "\n")

    segments = sum(len(v) for v in cases.values())
    print(f"wrote {out}: {len(cases)} cases, {segments} segments, "
          f"from {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
